apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://master.kubernetes.com:6443
    certificate-authority: /srv/kubernetes/ssl/ca.pem
    client-key: /srv/kubernetes/ssl/kube-apiserver-server.pem
    client-certificate: /srv/kubernetes/ssl/kube-apiserver-server.pem
    user: system
contexts:
- context:
    cluster: local
    user: system
  name: kubelet-context
current-context: kubelet-context
users:
- name: system
  user:
    token: fcpbN76HNF542pY4i1vWXpVbZZ43J1jU
